name: Code To Gitee
on:
  #监听push操作
  push:
    branches:
      # master分支，你也可以改成其他分支
      - devel
jobs:
  Sync-Code-To-Gitee-job:
    # runs-on 指定job任务运行所需要的虚拟机环境
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        # 支持Gitee, Github and Gitlab
        src: github/Daudxu
        # 支持Gitee, Github and Gitlab
        dst: gitee/nanjing_xuanmai_network
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        # 支持Github/Gitee的用户、组织以及Gitlab的组
        static_list: 'english-words-back'
        account_type: org
        force_update: true
        timeout: '600s'
        # 支持分别设置源和目的端的类型
        # src_account_type: org 0eca7fdcbc661c7ebfc1506a6ca1b836
        # dst_account_type: org